services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_LISTEN_ADDRESS=0.0.0.0
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - DB_SQLITE_POOL_SIZE=50
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - TZ=America/New_York
      
      # FIX: Allow login via HTTP IP address
      - N8N_SECURE_COOKIE=false
      
    volumes:
      - /mnt/pve/Seagate2TB/stacks/n8n:/home/node/.n8n
