services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    security_opt:
      - apparmor=unconfined
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - SETTINGS_ENCRYPTION_KEY=********************
      - DUPLICATI__WEBSERVICE_PASSWORD=***********
    volumes:
      - ./config:/config
      # Add specific paths that actually exist instead:
      # - /path/to/actual/data:/source/data:ro
    ports:
      - 8200:8200
    restart: unless-stopped
