services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    security_opt:
      - apparmor=unconfined
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - SETTINGS_ENCRYPTION_KEY=rzzLNpJJL4YulcLQHBY9xodwzmkV6lJ92HFjY0+ZvgQ=
      - DUPLICATI__WEBSERVICE_PASSWORD=niqrix-5fyrHy-fifnas
    volumes:
      - ./config:/config
      - /mnt/Seagate2TB/backup:/backups
      # Add specific paths that actually exist instead:
      # - /path/to/actual/data:/source/data:ro
    ports:
      - 8200:8200
    restart: unless-stopped
