## its for Adguard-Home

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    ports:
      # DNS - Mapped to your host IP
      - "0.0.0.0:53:53/tcp"
      - "0.0.0.0:53:53/udp"

      # Web Interface - Mapped to your host IP
      - â€œ0.0.0.0:8080:80/tcp"

      # Initial Setup - Mapped to your host IP
      - "0.0.0.0:3000:3000/tcp"
      
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
      
    networks:
      - adguard_net

networks:
  adguard_net:
    driver: bridge
